### ISSUE TITLE
Opening vs code from the command line doesn't open with prettier.

### ISSUE THREAD

**Issue by BruceHem** [remimarsal/prettier-now-vscode#2]
I don't know if this is a problem with the extension or vscode itselft, but when I open with the executable it loads prettier, but from the command line it doesn't.

@remimarsal any ideas? Does this happens to u?

**Comment by remimarsal** [comment]
Hi Bruce! :)

Thanks for reporting this. I tested it myself and calling VS Code from the command line doesn't seem to trigger the issue for me.

However it seems to happen when I have no file previously opened on the folder I open.

Can you confirm we're talking about the same issue? If you open some files and then close / reopen VS Code, does Prettier load ?

**Comment by BruceHem** [comment]
I think we have different problem, if i open vscode from the command line it doesn't trigger prettier, but if i close vscode then open it again, (not from commandline). 
It works.

**Comment by remimarsal** [comment]
@BruceHem Hey Bruce, I'm unable to reproduce your issue. 

Did you add Code in your terminal with the VS Code command "Install 'code' command in the PATH"? What system are you on and which version ?

I published today a fix for when the extension breaks if you have no active document at launch.

**Comment by BruceHem** [comment]
Seems to be working now.

**Comment by remimarsal** [comment]
Alright it was probably related then.. well that's great news! 👍 Thanks for reporting this issue
