### ISSUE TITLE
Validation Error with arrowParens

### ISSUE THREAD

**Issue by n1ghtmare** [remimarsal/prettier-now-vscode#37]
Hi guys,

There seems to be a config clash with Prettier and more specifically to the config setting `arrowParens`. Here is the output from vscode upon formatting:

```
● Validation Error:

  Option "arrowParens" must be of type:
    boolean
  but instead received:
    string

  Example:
  {
    "arrowParens": false
  }
```

The fix is simple, just add `prettier.arrowParens: false` (or `true` of course) in your config.

**Comment by matthias-ccri** [comment]
I'm seeing this too. My settings JSON does not have an `arrowParens` setting, and the error message doesn't tell me how to fix it.

Adding `"prettier.arrowParens": true,` to my settings JSON works to silence the error, BUT it creates a validation warning:

```
Incorrect type. Expected "string".
Value is not accepted. Valid values: "avoid", "always".
```

![image](https://user-images.githubusercontent.com/18034092/147684468-d2ff5789-20c6-45aa-a120-7382954578c1.png)

The warning doesn't seem to break anything, however.
