### ISSUE TITLE
Question: .ignore file support

### ISSUE THREAD

**Issue by jdichev** [remimarsal/prettier-now-vscode#5]
Hello,
Sorry for the question but is there support for .ignore files?
There seems to be none but not sure.
Thanks,
Jordan

**Comment by remimarsal** [comment]
Hi Jordan,

Not sure if you're referring to .gitignore files or something else. If that's the case, the syntax is not supported. 
On the other hand, if this .ignore file is actually a JS, TS, CSS, JSON, or GraphQL file but with a different extension, you can try to add its language ID in the extension settings (`javascriptEnable`, `typescriptEnable`, ...) .

For instance, the extension default parameters for `javascriptEnable` are `["javascript","javascriptreact"]`.

**Comment by jdichev** [comment]
Hi Remi,

Thanks for your answer. I was referring to .gitignore and similarly named files as I saw them supported by prettier-vscode only to discover this was added late after the fork. I still prefer prettier-now-vscode because of the flexibility. Perhaps such feature will be a nice addition. Are you open to it?
