### ISSUE TITLE
Doesn't seem to work with vetur for Vue

### ISSUE THREAD

**Issue by BruceHem** [remimarsal/prettier-now-vscode#6]
I don't know if you've used it with vue, but it doesn't seem to work. Or is there a workaround?

**Comment by johnpyp** [comment]
Expanding on this issue, I've had a lot of issues with prettier + vscode so far. The best solution was for me to set add "vue" as a language id in the main prettier plugin. This solved most of my troubles, however this solution doesn't work for prettier-now! Considering prettier-now has a huge upside in putting spaces before parenthesis, this was a big disappointment. It would be awesome if this bug could be fixed.

**Comment by Shuunen** [comment]
why is this issue closed @chanlito @remimarsal  ?

**Comment by chanlito** [comment]
@Shuunen I close this because I don't know if @remimarsal would want to support this or not?

**Comment by Shuunen** [comment]
I understand, he will choose whether its an issue or not
